[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_program = "Bm38NWQxWSRixVH7n6TtgZhuZo8NAji5MrUQZzviBd1f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet =  "/mnt/c/Users/Fadex/Desktop/final-module-sol-intermidiate/last_one/nft_program/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
